### ISSUE TITLE
Enable load balancing so multiple users can use multiple instances of the profile

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-service-armadillo#516]
Motivation: if many users are using same profile then the Rock instance gets overloaed
Solution: have sticky load balancing

**Comment by clemens-tolboom** [comment]
## Questions

- What is "many users"?
- Sticky is session connected?
- Do we 'see' instances in the UI
- Do we start/stop in bulk?

**Comment by clemens-tolboom** [comment]
In #544 I made note for load balancing not moved here

## Load balancing

Add image
Configure which service to balance (duplicate)
Name service `nginx` ie 'rock'
Name `serviceB1` ie `rockB1` etc.

```yml
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  serviceA:
    image: serviceA:latest
  serviceB1:
    image: serviceB:latest
  serviceB2:
    image: serviceB:latest
  serviceB3:
    image: serviceB:latest
```

### NGNX config

```ngnx
http {
    upstream backend {
        ip_hash;
        server serviceB1:8080;
        server serviceB2:8080;
        server serviceB3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header JSESSIONID $cookie_JSESSIONID;
        }
    }
}
```

**Comment by StuartWheater** [comment]
I take it request forwarding will need to have Session Affinity.

**Comment by clemens-tolboom** [comment]
## How to test load balancing

The `sticky` is not available in `image: nginx:latest` and learned `ip_hash` is not really an option.

## Working config

Using `armadillo-compose.zip` from pre release v4.0.2 I can run `release-test.R` using changed `docker-compose.yml`.

<details>

<summary>Changed docker-compose.yml making rock an nginx proxy</summary>

```yml
version: "3.4"
services:
  armadillo:
    hostname: armadillo
    ports:
      - 8080:8080

    build:
      context: '.'
      dockerfile: 'Dockerfile'
      args:
        JAR_FILE: '*.jar'

    image: molgenis/molgenis-armadillo:latest
    environment:
      LOGGING_CONFIG: 'classpath:logback-file.xml'
      AUDIT_LOG_PATH: '/app/logs/audit.log'
      SPRING_SECURITY_USER_PASSWORD: 'admin'
    volumes:
      - ${PWD}/armadillo/logs:/logs
      - ${PWD}/armadillo/data:/data
      - ${PWD}/armadillo/config:/config
      - /var/run/docker.sock:/var/run/docker.sock

  default:
    hostname: default
    image: datashield/rock-base:latest
    environment:
      DEBUG: "TRUE"

  xenon:
    hostname: xenon
    image: datashield/rock-dolomite-xenon:latest
    environment:
      DEBUG: "TRUE"


  # Armadillo think this is a rock server
  rock:
    image: nginx:latest
    # Only exposed for testing load balancing
    ports:
      - 8085:8085
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rockB1
      - rockB2
      - rockB3

  rockB1:
    image: datashield/rock-base:latest
    environment:
      DEBUG: "TRUE"

  rockB2:
    image: datashield/rock-base:latest
  
  rockB3:
    image: datashield/rock-base:latest
```
</summary>

**Comment by clemens-tolboom** [comment]
## HAProxy

HA Proxy may be an alternative for `nginx.sticky`

- http://docs.haproxy.org/2.9/configuration.html#2.7
- https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html#example-with-haproxy

```yml
# ./docker-compose.yml
...
  haproxy:
    image: haproxy:2.3
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8081:80
```

and

```
# ./haproxy.cfg

# haproxy -c -f /etc/haproxy/haproxy.cfg

global
    log /dev/log    local0
    log /dev/log    local1 notice
    # chroot /var/lib/haproxy
    # stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    # stats timeout 30s
    # user haproxy
    # group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    # errorfile 400 /etc/haproxy/errors/400.http
    # errorfile 403 /etc/haproxy/errors/403.http
    # errorfile 408 /etc/haproxy/errors/408.http
    # errorfile 500 /etc/haproxy/errors/500.http
    # errorfile 502 /etc/haproxy/errors/502.http
    # errorfile 503 /etc/haproxy/errors/503.http
    # errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
   bind *:80
   default_backend http_back

backend http_back
   balance roundrobin
   cookie JSESSIONID prefix nocache
   server server1 build2be.nl:80  cookie s1 check
   server server2 build2be.com:80 cookie s2 check
```
