### ISSUE TITLE
Empty user when oidc user not set

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-service-armadillo#634]
How to reproduce:

Start armadillo with oAuth config, but without oidc user in application.yml:
```
 # uncomment this to configure an oidc user as admin user
 # oidc-admin-user: user@yourdomain.org
```
```
    oauth2:
      client:
        provider:
          molgenis:
            issuer-uri: 'http://auth.molgenis.org'
        registration:
          molgenis:
            client-id: '...'
            client-secret: '...'
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.molgenis.org'
        opaquetoken:
         client-id: '...'
```

Go to the user table in the browser. 

Expected:
no users, or one line with "admin", ideally this one also cannot be disabled as admin

Observed:
empty line (the local admin user doesn't have an email address)
