### ISSUE TITLE
Can we set DataSHIELD options like permissive mode

### ISSUE THREAD

**Issue by clemens-tolboom** [molgenis/molgenis-service-armadillo#651]
## UI

Using the UI we can add this

![image](https://github.com/molgenis/molgenis-service-armadillo/assets/371014/bc0913ad-6fc2-48c6-967b-116e03da345e)

## Swagger

Using swagger API it is possible to PUT a new profile

```json
{
    "name": "rock",
    "image": "datashield/rock-base:latest",
    "host": "localhost",
    "port": 6313,
    "packageWhitelist": [
      "dsBase"
    ],
    "functionBlacklist": [],
    "options": {
      "datashield.seed": "123456789",
      "datashield.privacyControlLevel": "permissive"
    },
    "container": {
      "tags": [
        "datashield/rock-base:latest"
      ],
      "status": "RUNNING"
    }
}
```

## Armadillo compose (not tested)

Add it to `application.yml` profile

```yml
  profiles:
    - name: default
      image: datashield/rock-base:latest
      port: 8085
      host: default
      package-whitelist:
        - dsBase
      function-blacklist: [ ]
      options:
        datashield:
          # the seed can only be 9 digits
          seed: 123456789
          privacyControlLevel: "permissive"
```

## R?

Not sure how to test
